### ISSUE TITLE
can't catch exception while uploading file

### ISSUE THREAD

**Issue by ghost** [jrm2k6/cloudder#26]
I am trying 
try{ 
 Cloudder::upload($request->file('profile_picture'),
          null,
          array("format" => "jpg", "crop" => "crop", "x" => 0, "y" => 0, "width" => 200, "height" => 200,"crop" => "thumb", "gravity" => "face", )
    );
}
catch(Exception $e){
return 'invalid';
}

i am trying to upload a invalid file (abc.txt)  so it must come in catch but  i get HTTP/1.1 500 Internal Server Error

**Comment by jrm2k6** [comment]
@janoop  I am trying to reproduce the error here https://github.com/jrm2k6/cloudder-l5-sample-project/blob/cloudder-issue-26/app/Console/Commands/UploadPictureCommand.php

I specify a wrong file name for the image, and what I get is:

```

  [Cloudinary\Error]
  Error in sending request to server - couldn't open file "/Users/jrm2k6/Workspace/Perso/cloudder-l5-sample-project/public/ktten.jpg"
```

I am running it as a console command so that might be why you get a 500. Could you put a breakpoint or some logging in the ```report``` method of  ```Handler.php``` in your Laravel project?

**Comment by ghost** [comment]
**`I specify a wrong file name for the image, and what I get is:`**
I am sending a valid  file (location) but with invalid format i.e., abc.txt

so i just wanted to know why can't i catch it in my catch block 

and also i am a  beginner in laravel so i am not sure that if it is possibe to catch `Cloudinary\Error` but all i can see  in upload.php is that LINE 4     `class Error extends \Exception {}; ` so i think it can be catched.

my expected output is ` invalid` because i am catching it but i get:



```
[2016-12-28 04:55:42] local.ERROR: Cloudinary\Error: Invalid image file in /srv/laravel/vendor/cloudinary/cloudinary_php/src/Uploader.php:322
Stack trace:
#0 /srv/laravel/vendor/cloudinary/cloudinary_php/src/Uploader.php(62): Cloudinary\Uploader::call_api('upload', Array, Array, Object(Illuminate\Http\UploadedFile))
#1 /srv/laravel/vendor/jrm2k6/cloudder/src/JD/Cloudder/CloudinaryWrapper.php(122): Cloudinary\Uploader::upload(Object(Illuminate\Http\UploadedFile), Array)
#2 /srv/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): JD\Cloudder\CloudinaryWrapper->upload(Object(Illuminate\Http\UploadedFile), NULL, Array)
#3 /srv/laravel/app/Http/Controllers/SignupController.php(202): Illuminate\Support\Facades\Facade::__callStatic('upload', Array)
#4 [internal function]: App\Http\Controllers\SignupController->profileupload(Object(Illuminate\Http\Request))
#5 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#6 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('profileupload', Array)
#7 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\SignupController), 'profileupload')
#8 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#9 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /srv/laravel/app/Http/Middleware/checkstatus.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\checkstatus->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /srv/laravel/app/Http/Middleware/checklogin.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\checklogin->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /srv/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /srv/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /srv/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /srv/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /srv/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#38 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /srv/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#40 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /srv/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /srv/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /srv/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /srv/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /srv/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /srv/http/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}  

```

**Comment by jrm2k6** [comment]
@janoop No worries, I will try to reproduce with an invalid file extension.

Yes you should be able to catch it easily as they extend the same class.

**Comment by jrm2k6** [comment]
Why did you close it? Where you able to fix this issue? Anything the
package should do differently?

**Comment by ghost** [comment]
there is no problem in your package it was me. 
Actually i have learn java first so there you don't need to import any thing to use exception i thought same for php but i was wrong i googled about exception in php and i get that i need to put use exception in top to use exception.

Sorrry for wasting time, my bad..
sorry again.

**Comment by jrm2k6** [comment]
No worries! Thanks for explaining.
